<?php

/**
 * Implements hook_action_info().
 * Registers custom VBO actions as Drupal actions.
 */
function id_actions_action_info() {
  $actions = array();
  $files = id_actions_load_action_includes();
  foreach ($files as $filename) {
    $action_info_fn = 'id_actions_'. str_replace('.', '_', basename($filename, '.inc')).'_info';
    $action_info = call_user_func($action_info_fn);
    if (is_array($action_info)) {
      $actions += $action_info;
    }
  }

  return $actions;
}

/**
 * Loads the VBO actions placed in their own include files (under actions/).
 *
 * @return
 *   An array of containing filenames of the included actions.
 */
function id_actions_load_action_includes() {
  static $loaded = FALSE;

  // The list of VBO actions is fairly static, so it's hardcoded for better
  // performance (hitting the filesystem with file_scan_directory(), and then
  // caching the result has its cost).
  $path = drupal_get_path('module', 'id_actions') . '/actions/';
  $files = array(
    'extra.action.inc',
    'extra1.action.inc',
    'extra2.action.inc',
    'extraplus.action.inc',
    'extraplus1.action.inc',
  );

  if (!$loaded) {
    foreach ($files as $file) {
      include_once $path . $file;
    }
    $loaded = TRUE;
  }

  return $files;
}
